### ISSUE TITLE
SA Payment icons image is too big 

### ISSUE THREAD

**Issue by tolu-paystack** [tubiz/woo-paystack#33]
Hey @tubiz, I noticed you removed the inline style I put on the image for SA payment icons. I had put that there because for some reason, the image was too large on checkout (even when set to the same dimensions as the NG and GH ones). I don't know if you know another way we could resize it, but that was all I was able to come up with
![screencapture-shopstack-io-checkout-2020-09-29-18_09_25](https://user-images.githubusercontent.com/60101507/94719961-c3f55d80-034b-11eb-9e86-bc35d6195862.png)

**Comment by tubiz** [comment]
@tolu-paystack the issue with the logo is with the theme you are using. Adding the inline style for all users might fix the display issue on the theme you are using and then make the logo smaller on other themes. 

It is better for the style to be added to the site and not in the plugin globally for all users.
