### ISSUE TITLE
Only show Paystack notice on WooCommerce sections

### ISSUE THREAD

**Issue by jobthomas** [tubiz/woo-paystack#72]
I've installed Paystack in test mode, and the result is a persistent notice following me around:

![](https://share.cleanshot.com/QvOqH7+)

My suggestion would be:

* Only limit this notice to the WooCommerce domain in the WP Admin
* If possible, also allow the option close the notice. I'm aware that I'm in test mode, I don't need to be constantly reminded of that.

**Comment by tubiz** [comment]
Fixed via #83
