### ISSUE TITLE
Compatibility with WooCommerce Checkout Block

### ISSUE THREAD

**Issue by jobthomas** [tubiz/woo-paystack#73]
WooCommerce now has an amazing checkout block, but the Paystack plugin is not compatible with it. When using the checkout block, Paystack simply doesn't show up as a payment option.

**Comment by nielslange** [comment]
See also https://github.com/woocommerce/woocommerce-blocks/issues/11003 and https://github.com/woocommerce/woocommerce-blocks/issues/10993

**Comment by nielslange** [comment]
No worries, and thanks for the heads-up, @tubiz! 🙌

**Comment by tubiz** [comment]
Fixed in #87
